/** tools/defs.ts — Tool schema definitions (JSON schema only, no implementation) */
// NOTE: SPAWN_AGENT_DEFINITION is defined inline here (not imported from spawn-agent.ts)
// to break the circular dependency: defs→spawn-agent→gateway→providers→tools-format→defs

export const TOOL_DEFINITIONS = [
  { name: 'read_file',     description: 'Read file contents with line numbers. Max 50k chars.',
    input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'write_file',    description: 'Write content to a file, creating directories as needed.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, content: { type: 'string' } }, required: ['path', 'content'] } },
  { name: 'edit_file',     description: 'Replace old_string with new_string (first occurrence). old_string must match exactly.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, old_string: { type: 'string' }, new_string: { type: 'string' } }, required: ['path', 'old_string', 'new_string'] } },
  { name: 'edit_file_all', description: 'Replace ALL occurrences of old_string with new_string in a file.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, old_string: { type: 'string' }, new_string: { type: 'string' } }, required: ['path', 'old_string', 'new_string'] } },
  { name: 'apply_patch',   description: 'Apply a unified diff patch to a file.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, patch: { type: 'string' } }, required: ['path', 'patch'] } },
  { name: 'make_dir',      description: 'Create a directory and parents.',
    input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'delete_file',   description: 'Delete a file.',
    input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'run_command',   description: 'Run a shell command (git, npm, tests, builds). Timeout 30s.',
    input_schema: { type: 'object', properties: { command: { type: 'string' } }, required: ['command'] } },
  { name: 'bash',          description: 'Alias for run_command.',
    input_schema: { type: 'object', properties: { command: { type: 'string' } }, required: ['command'] } },
  { name: 'search_files',  description: 'Regex search in files via ripgrep (falls back to grep).',
    input_schema: { type: 'object', properties: { pattern: { type: 'string' }, path: { type: 'string' }, glob: { type: 'string' } }, required: ['pattern'] } },
  { name: 'list_files',    description: 'List files in a directory (up to 100).',
    input_schema: { type: 'object', properties: { pattern: { type: 'string' } }, required: ['pattern'] } },
  { name: 'glob',          description: 'Find files matching a glob pattern. Returns up to 200 paths.',
    input_schema: { type: 'object', properties: { pattern: { type: 'string', description: 'e.g. "src/**/*.ts"' } }, required: ['pattern'] } },
  { name: 'repo_map',      description: 'Symbol-aware repo tree — shows functions/classes per file.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, depth: { type: 'number' } } } },
  { name: 'symbol_graph',  description: 'Cross-file symbol graph: where `symbol` is defined and every file that references it. Use before renames or to gauge blast radius of a change.',
    input_schema: { type: 'object', properties: { symbol: { type: 'string', description: 'Identifier to look up (letters, digits, underscore only)' }, path: { type: 'string', description: 'Repo root to scan (default: current directory)' }, json: { type: 'boolean', description: 'Return JSON instead of human-readable text' } }, required: ['symbol'] } },
  { name: 'git_status',    description: 'Show git status: staged, unstaged, untracked.',
    input_schema: { type: 'object', properties: {} } },
  { name: 'git_diff',      description: 'Show unified diff. Optional: specific path or --staged.',
    input_schema: { type: 'object', properties: { path: { type: 'string' }, staged: { type: 'boolean' } } } },
  { name: 'git_log',       description: 'Show recent commits (default 10).',
    input_schema: { type: 'object', properties: { n: { type: 'number' } } } },
  { name: 'git_commit',    description: 'Stage all changes and commit with message.',
    input_schema: { type: 'object', properties: { message: { type: 'string' } }, required: ['message'] } },
  { name: 'checkpoint',    description: 'git stash checkpoint before risky changes. User can restore with git stash pop.',
    input_schema: { type: 'object', properties: { description: { type: 'string' } }, required: ['description'] } },
  { name: 'git_branch',   description: 'List branches or create/checkout a new branch.',
    input_schema: { type: 'object', properties: { name: { type: 'string' }, checkout: { type: 'boolean' } } } },
  { name: 'git_push',     description: 'Push current branch to remote. Supports --force-with-lease.',
    input_schema: { type: 'object', properties: { remote: { type: 'string' }, branch: { type: 'string' }, force: { type: 'boolean' } } } },
  { name: 'git_stash',    description: 'Stash management: list, pop, apply, drop.',
    input_schema: { type: 'object', properties: { action: { type: 'string', enum: ['list', 'pop', 'apply', 'drop'] }, index: { type: 'number' } } } },
  { name: 'git_patch',    description: 'Apply a unified diff patch via git apply. Optionally commit.',
    input_schema: { type: 'object', properties: { patch: { type: 'string' }, commit: { type: 'boolean' }, message: { type: 'string' } }, required: ['patch'] } },
  { name: 'git_auto_message', description: 'Generate a conventional commit message from staged diff using AI.',
    input_schema: { type: 'object', properties: {} } },
  { name: 'web_fetch',     description: 'Fetch a URL. Returns text body up to 50k chars.',
    input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'web_search',    description: 'Search the web via DuckDuckGo. Returns titles, URLs, snippets.',
    input_schema: { type: 'object', properties: { query: { type: 'string' }, max_results: { type: 'number' } }, required: ['query'] } },
  { name: 'qmd_search',        description: 'Semantic + keyword search over project docs via QMD (requires qmd install).',
    input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'search_knowledge',  description: 'FTS5 search over indexed files + persistent memory. No external deps. Use before qmd_search.',
    input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'index_files',       description: 'Index source files in a directory into the local FTS5 knowledge base for search_knowledge.',
    input_schema: { type: 'object', properties: { path: { type: 'string', description: 'Directory to index (default: cwd)' } } } },
  { name: 'save_memory',   description: 'Save a note to persistent memory (SQLite). Persists across sessions.',
    input_schema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] } },
  { name: 'read_memory',   description: 'Read persistent memory. Use at session start to recall context.',
    input_schema: { type: 'object', properties: {} } },
  { name: 'write_todos',   description: 'Set session TODO list. Use to track multi-step tasks.',
    input_schema: { type: 'object', properties: { todos: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, text: { type: 'string' }, done: { type: 'boolean' } }, required: ['id', 'text', 'done'] } } }, required: ['todos'] } },
  { name: 'ask_user',      description: 'Ask user a question. Use before irreversible actions.',
    input_schema: { type: 'object', properties: { question: { type: 'string' }, choices: { type: 'array', items: { type: 'string' } } }, required: ['question'] } },
  { name: 'execute_code', description: 'Execute Python or JavaScript code in a sandboxed environment. Use for data processing, calculations, file transformations. Output is captured stdout.',
    input_schema: { type: 'object', properties: {
      language: { type: 'string', enum: ['python', 'javascript'] },
      code: { type: 'string' },
      timeout: { type: 'number', description: 'Timeout in seconds (default 30, max 120)' }
    }, required: ['language', 'code'] } },
  { name: 'browser', description: 'Browser automation: navigate, snapshot, click, type, fill, screenshot, find, get, batch, eval, vision. Actions: navigate|snapshot|click|type|fill|screenshot|find|get|batch|eval|extract|search|vision. Use `vision` to get a natural-language description of the rendered page from a screenshot — good for "does this UI look right?" questions the DOM cannot answer.',
    input_schema: { type: 'object', properties: {
      action: { type: 'string', enum: ['navigate', 'snapshot', 'click', 'type', 'fill', 'screenshot', 'find', 'get', 'batch', 'eval', 'extract', 'search', 'vision'] },
      url: { type: 'string' },
      selector: { type: 'string', description: 'CSS selector or @ref (e.g., "#btn" or "@e1")' },
      text: { type: 'string' },
      role: { type: 'string', description: 'ARIA role for find action (e.g., "button", "textbox")' },
      findAction: { type: 'string', description: 'Action for find (e.g., "click", "fill")' },
      name: { type: 'string', description: 'Accessible name for find action' },
      info: { type: 'string', description: 'What to get: text|html|title|url|value|attr' },
      js: { type: 'string', description: 'JavaScript to evaluate' },
      query: { type: 'string' },
      prompt: { type: 'string', description: 'For action=vision: the question to ask about the screenshot (defaults to "describe the visible page").' },
      screenshot: { type: 'string', description: 'For action=vision: optional path to an existing screenshot file; if absent, a new screenshot is taken.' },
      interactive: { type: 'boolean', description: 'Only show interactive elements in snapshot' },
      compact: { type: 'boolean', description: 'Remove empty structural elements' },
      depth: { type: 'number', description: 'Limit snapshot tree depth' },
      annotate: { type: 'boolean', description: 'Add numbered labels on screenshot' },
      path: { type: 'string', description: 'Screenshot save path' },
      commands: { type: 'array', items: { type: 'array', items: { type: 'string' } }, description: 'Batch commands array' }
    }, required: ['action'] } },
  { name: 'session_search', description: 'Search across all previous chat sessions for context. Finds relevant past conversations.',
    input_schema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  {
    name: 'spawn_agent',
    description: 'Spawn a focused sub-agent for a specific task. Types: explore (read-only file search), plan (analysis + web), verify (read + bash), code (read/write/edit files + bash), research (web + browser + files). Returns sub-agent output as a string.',
    input_schema: {
      type: 'object' as const,
      properties: {
        type: { type: 'string', enum: ['explore', 'plan', 'verify', 'code', 'research', 'custom'], description: 'Sub-agent type determining allowed tools' },
        task: { type: 'string', description: 'The task or question for the sub-agent to complete' },
        tools: { type: 'array', items: { type: 'string' }, description: 'Custom tool list when type=custom' },
        model: { type: 'string', description: 'Override model for sub-agent (defaults to parent model)' },
      },
      required: ['type', 'task'],
    },
  },
  { name: 'orchestrate', description: 'Plan-then-execute-then-verify workflow for complex multi-step tasks. Chains three sub-agents: planner -> coder -> verifier.',
    input_schema: { type: 'object', properties: { task: { type: 'string', description: 'The full task description' } }, required: ['task'] } },
  { name: 'memory_graph_add', description: 'Add a node to the memory graph (Qdrant-backed knowledge graph).',
    input_schema: { type: 'object', properties: { node: { type: 'string', description: 'Node name/ID' }, content: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['node', 'content'] } },
  { name: 'memory_graph_query', description: 'Semantic search over the memory graph.',
    input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
  { name: 'memory_graph_link', description: 'Create a relationship between two memory graph nodes.',
    input_schema: { type: 'object', properties: { fromNode: { type: 'string' }, toNode: { type: 'string' }, relation: { type: 'string' } }, required: ['fromNode', 'toNode', 'relation'] } },
  { name: 'memory_graph_prune', description: 'Remove memory graph nodes older than N days.',
    input_schema: { type: 'object', properties: { olderThanDays: { type: 'number' } }, required: ['olderThanDays'] } },
  { name: 'deploy_trigger', description: 'Trigger a deployment pipeline for a service.',
    input_schema: { type: 'object', properties: { service: { type: 'string' }, branch: { type: 'string' } }, required: ['service'] } },
  { name: 'deploy_status', description: 'Check the deployment status of a service.',
    input_schema: { type: 'object', properties: { service: { type: 'string' } }, required: ['service'] } },
];
